### ISSUE TITLE
cannot import name 'sqrt_fixed'- a chainer cuda issue!

### ISSUE THREAD

**Issue by ashar-ali** [takumayagi/fpl#3]
Hi @takumayagi ,

Thanks for providing the code. I am new to chainer. I followed the exact same steps as you have mentioned and set up an environment with chainer v4.0, cuda 8, and cudnn 5.1, cupy for cuda8.0 and so on, with an Nvidia Titan X GPU. 

Still whenever i import cuda from chainer, I get the following error-

cannot import name 'sqrt_fixed'.

Is this a common error? I ask this because I could not find anything similar on the github issues pages of Chainer.

Thanks,
Ashar

**Comment by ashar-ali** [comment]
BTW the code works just fine when I modify it to use without any cuda support.

**Comment by bbidong** [comment]
it is not a common error, I  have not meet it.

**Comment by takumayagi** [comment]
@ashar-ali 
Hi Ashar, thank you for having interest & sorry for my late response.
I think this is a cupy issue rather than a chainer issue.
Cupy is a numpy-like array library which can run CUDA code.
https://github.com/cupy/cupy

I'd recommend installing the binary package of it.
```
pip install cupy-cuda80
```

Hope this will help you.

**Comment by bbidong** [comment]
Hi @ashar-ali,
I run the demo successfully, and i am trying make my dataset work well. could we have a talk?
